apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application
  namespace: final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 3
