apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: final
spec:
  type: LoadBalancer
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
