apiVersion: v1
kind: Pod
metadata:
  name: awscli-test
  namespace: final
spec:
  containers:
    - name: awscli
      image: amazon/aws-cli
      command: ["/bin/sh"]
      args: ["-c", "aws s3 ls"]

  restartPolicy: Never
